### ISSUE TITLE
 Error:  File "C:\Python27\lib\os.py", line 425, in __getitem__     return self.data[key.upper()]

### ISSUE THREAD

**Issue by shaunakganorkar** [mvrozanti/RAT-via-Telegram#39]
I keep getting the following error no matter what I try? Any help will be great.

Traceback (most recent call last):  File "C:\Users\ \Downloads\RAT-via-Telegram-master\RATAttack.py", line 35, in <module>  token = os.environ['RAT_Token']
  
File "C:\Python27\lib\os.py", line 425, in __getitem__   return self.data[key.upper()]                                                                                       
KeyError: 'RAT_Token'

**Comment by mvrozanti** [comment]
You need a Telegram Bot Key to host your bot. Once you have it, you can set it as an environment variable or just replace `os.environ...` by your key.
