### ISSUE TITLE
How to run it in Linux?

### ISSUE THREAD

**Issue by shuhrat02** [mvrozanti/RAT-via-Telegram#40]
Hi guys! tnx for this awesome RAT! have an issue, how to run it in Linux? Does this RAT support a linux platform? or only windows?

Logs:
> pip install pyHook-1.5.1-cp27-cp27m-win_amd64.whl
> pyHook-1.5.1-cp27-cp27m-win_amd64.whl is not a supported wheel on this platform.
> 
> pip install pyHook
> Collecting pyHook
>   Could not find a version that satisfies the requirement pyHook (from versions: )
> No matching distribution found for pyHook
> 
> python RATAttack.py
> Traceback (most recent call last):
>   File "RATAttack.py", line 4, in <module>
>     from PIL import ImageGrab               # /capture_pc
>   File "/usr/lib/python2.7/dist-packages/PIL/ImageGrab.py", line 22, in <module>
>     raise ImportError("ImageGrab is macOS and Windows only")
> ImportError: ImageGrab is macOS and Windows only

**Comment by shuhrat02** [comment]
There is a Linux implementation of pyHook called pyxhook. does not work :(

**Comment by mvrozanti** [comment]
This is made to run on Windows only for now. But I'd be glad if this were to be cross-platform since Python can be. Very nice idea. I'll accept pull requests on this

Good resources: 
https://stackoverflow.com/questions/1325581/how-do-i-check-if-im-running-on-windows-in-python#1325587

https://stackoverflow.com/questions/31259856/how-to-create-an-executable-file-for-linux-machine-using-pyinstaller#32157287

**Comment by mvrozanti** [comment]
@shuhrat02 [This might be relevant](https://www.linuxquestions.org/questions/programming-9/%5Bpython%5D-pyhook-equivalent-for-linux-4175521261/)
