### ISSUE TITLE
Bad HTTP Response

### ISSUE THREAD

**Issue by moneak** [mvrozanti/RAT-via-Telegram#45]
I get so many similar errors:

```
BadHTTPResponse: (404, u'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL /bot(my token)/getUpdates was not found on this server.</p>\n<hr>\n<address>Apache/2.2.15 (CentOS) Server at api.telegram.org Port 443</address>\n</body></html>\n', <urllib3.response.HTTPResponse object at 0x041EB150>)
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\telepot\__init__.py", line 1183, in get_from_telegram_server
    allowed_updates=allowed_upd)
  File "C:\Python27\lib\site-packages\telepot\__init__.py", line 1000, in getUpdates
    return self._api_request('getUpdates', _rectify(p))
  File "C:\Python27\lib\site-packages\telepot\__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "C:\Python27\lib\site-packages\telepot\api.py", line 155, in request
    return _parse(r)
  File "C:\Python27\lib\site-packages\telepot\api.py", line 136, in _parse
    raise exception.BadHTTPResponse(response.status, text, response)
BadHTTPResponse: (404, u'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL /bot(my token)/getUpdates was not found on this server.</p>\n<hr>\n<address>Apache/2.2.15 (CentOS) Server at api.telegram.org Port 443</address>\n</body></html>\n', <urllib3.response.HTTPResponse object at 0x041EBC10>)
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\telepot\__init__.py", line 1183, in get_from_telegram_server
    allowed_updates=allowed_upd)
  File "C:\Python27\lib\site-packages\telepot\__init__.py", line 1000, in getUpdates
    return self._api_request('getUpdates', _rectify(p))
  File "C:\Python27\lib\site-packages\telepot\__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "C:\Python27\lib\site-packages\telepot\api.py", line 155, in request
    return _parse(r)
  File "C:\Python27\lib\site-packages\telepot\api.py", line 136, in _parse
    raise exception.BadHTTPResponse(response.status, text, response)
BadHTTPResponse: (404, u'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL /bot(my token)/getUpdates was not found on this server.</p>\n<hr>\n<address>Apache/2.2.15 (CentOS) Server at api.telegram.org Port 443</address>\n</body></html>\n', <urllib3.response.HTTPResponse object at 0x041EE950>)
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\telepot\__init__.py", line 1183, in get_from_telegram_server
    allowed_updates=allowed_upd)
  File "C:\Python27\lib\site-packages\telepot\__init__.py", line 1000, in getUpdates
    return self._api_request('getUpdates', _rectify(p))
  File "C:\Python27\lib\site-packages\telepot\__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "C:\Python27\lib\site-packages\telepot\api.py", line 155, in request
    return _parse(r)
  File "C:\Python27\lib\site-packages\telepot\api.py", line 136, in _parse
    raise exception.BadHTTPResponse(response.status, text, response)
BadHTTPResponse: (404, u'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL /bot(my token)/getUpdates was not found on this server.</p>\n<hr>\n<address>Apache/2.2.15 (CentOS) Server at api.telegram.org Port 443</address>\n</body></html>\n', <urllib3.response.HTTPResponse object at 0x041EE0F0>)
```

**Comment by mvrozanti** [comment]
When exactly do you get many similar errors?

**Comment by dudeisbrendan03** [comment]
Telegram was releasing new features that affected the API on the 27th of August, does it work now?

On the 27th there was an update for the client and slight downtime on the API during the release of the newer version of Telegram passport.

**Comment by mvrozanti** [comment]
I guess I'm closing this.
