### ISSUE TITLE
DLL Load failed / Specified module cannot be found

### ISSUE THREAD

**Issue by dudeisbrendan03** [mvrozanti/RAT-via-Telegram#71]
```
Traceback (most recent call last):
  File ".\RATAttack.py", line 11, in <module>
    from winshell import startup                                                        # persistence
  File "C:\Users\Terri\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\winshell.py", line 31, in <module>
    from win32com import storagecon
  File "C:\Users\Terri\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\win32com\__init__.py", line 5, in <module>
    import win32api, sys, os
ImportError: DLL load failed: The specified module could not be found.
```

Can't get this to work, tried using info from other issues like #63 which seemed similar but I've gave up.
Been trying for a while now and it just doesn't want to work.

I've tried in the Windows Store ver of Python and the python org version. Neither worked, I'm using Python 3.7.3.

Any ideas?

(Running Windows 10 20H1/18922)
![image](https://user-images.githubusercontent.com/6009600/60458769-63064380-9c37-11e9-98c7-87ee325b63b2.png)
![image](https://user-images.githubusercontent.com/6009600/60458785-6994bb00-9c37-11e9-9eb2-cbe271ab3a85.png)
*(It says 1903 because that was the last stable release, more info about the 20H1 flight [here](https://blogs.windows.com/windowsexperience/2019/06/19/announcing-windows-10-insider-preview-build-18922/#GyIJtE0be9G551gG.97)*)

**Comment by mvrozanti** [comment]
I'm guessing the problem isn't with `os` or  `sys` modules. So the culprit must be `win32api`.

Maybe [this is a fix](https://stackoverflow.com/questions/3580855/where-to-find-the-win32api-module-for-python)?
