### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by haiderabbas2022** [mvrozanti/RAT-via-Telegram#85]
steps of what I did:

step 1: i downloaded the zip file for this and extracted.
step 2: installed python 3.7
step 3: opened RATAttack.py file and added token I got from botfather and my chat id
step 4: saved the file and ran compile.py
END

now what happened in result.

1. a folder appeared in same directory with a name __pycache__ that contained a file that apparently does nothing
2. got a new folder here "C:\Users\{THIS_IS_MY_USERNAME}\AppData\Roaming\" that contains an exe file and it also apparently does nothing.

if I send a msg to my bot. i will not respond.

any help is appreciated

**Comment by mvrozanti** [comment]
Can you run `python RATAttack.py` and post the output?

**Comment by haiderabbas2022** [comment]
Thanks for your reply.

this is what I get.

PS C:\Users\{MY_USERNAME}\Downloads\Compressed\RAT-via-Telegram-master\RAT-via-Telegram-master> python RATAttack.py                                                                                                                                 Traceback (most recent call last):
  File "RATAttack.py", line 11, in <module>
    from winshell import startup                                              # persistence
  File "C:\Users\{MY_USERNAME}\AppData\Local\Programs\Python\Python37\lib\site-packages\winshell.py", line 30, in <module>
    import win32con
ModuleNotFoundError: No module named 'win32con'


after that i tried to install win32con by using commands
python -m pip install win32con
and
pip install win32con

but both of these commands give error as win32con is not a module or it is not found. I have pypiwin32 already installed.
I dream if replacing win32con with pypiwin32 on file winshell.py on line 30 will fix the issue.

could you please tell me about this problem.

**Comment by mvrozanti** [comment]
I honestly have no clue man. Have you tried [this](https://stackoverflow.com/a/61448846)?
